### PR TITLE
Adding responsive table to ease use in mobile devices

### PR DESCRIPTION
**Pull request by ibnishak**
Switches to block display mode when initial page is loaded in mobile devices

### CODE REVIEW

**Comment by Arlen22** [comment]
Thank you, I will take a look at this soon, hopefully.

**Comment by Arlen22** [comment]
Where did you get the icons? Did you find them online? Make them yourself?

**Comment by ibnishak** [comment]
Ah, the icons were supposed to be part of pull request. Sorry, I am not exactly familiar with the git flow. I found the icons online, and thought it would be ok to use them for personal use. It was, again, not intended to be part of PR.

**Comment by Arlen22** [comment]
Ah, I see Ok, no problem.

**Comment by Arlen22** [comment]
I cherry picked the other commit, as well as my own addition to it. I will now close this pull request. Thank you very much.

**Pull request closed without merging**
