### PR TITLE
chore: many refactors/changes (see notes)

### PR DESCRIPTION
**Pull request by someguynamedmatt**
This is a _huge_ PR, apologies. 

- converted most of the files to TypeScript
- removed tiddlywiki as a hard-coded file, added as an npm dependency
- updated build process to copy TS output/assets to /build
- removed /lib, which seemed to be coming from webpack (see webpack note at the bottom)
- refactored authRoute.ts
- added cookies.ts (moved cookie-specific functions out of authRoute.ts)

### First
`npm install` (to get all the dependencies pulled in)

### To build it 
`npm run build`
or
`npm run build:clean` (this one removes the build dir before rebuilding)

`node ./build/server.js {path-to-settings-file}` 

### To install it globally
`npm run build:clean`
`npm link`
`tiddlyserver {path-to-settings-file}`

`npm unlink`

Again, this is a big PR, I'm definitely open to discussing some of the changes in here. As far as my testing went (manual, I'd like to add a testing lib though) it all seems to work the same, but my knowledge of how it works as an encompassing whole is limited to simple auth logins and tiddler creation.

### Webpack note
As far as I can tell, this project can't work with a webpack bundler due to its dynamic `require` statements. Webpack's static analysis can't determine what it needs, so things go missing. I might be wrong on this, but in my testing that's what it seemed like. Ideally, webpack would be used because it's more of a standard, but that would require some pretty hefty refactoring. I left the edited file in the commits as an example.

### CODE REVIEW

**Comment by Arlen22** [comment]
Thank you. I will take a look at what you've done hopefully in the next few days. Just wanted to comment that the two require warnings that webpack gives are expected and are due to two places that I use a custom require call. It still compiles properly and I have written the code to account for it.

**Comment by someguynamedmatt** [comment]
@Arlen22 Good to know! Where are those two points, btw (out of curiosity)? 

Also, would you find Docker helpful for this project and/or tests? I’d like to contribute as much as possible.

Also, if we can standardize the build process, whether that be with webpack or the cp-ing that’s being done here, we can have this project distributed on npm. That would make its bar-to-entry a little lower which is a plus.

**Comment by Arlen22** [comment]
I remember one is in boot.js because it has a require call if a module is not found and therefore has to be accounted for. The other one is preflighter.js, https.js or else the dynamic tree loading. The call is in server.ts I think, but I'm not sure.

I would like to move this forward to using webpack for the whole build I think. I'm not really thinking of using docker, but npm is definitely a good idea. Up to this point I had not used webpack to keep things simpler, but I use webpack + typescript for most of my work, and it is pretty simple to setup. However, the TypeScript types are heavily involved  and I don't really know how to build those, but it would be great if we could. 

The server[.js] file in the root is intended to be more of a bin file (like tiddlywiki.js) where as `src/server.ts` is the main entry point of the "library" part of TiddlyServer. I hope that makes sense.

**Comment by Arlen22** [comment]
The tiddlywiki folder is an optimized version of TiddlyWiki which is intented for production use. There is a feature in the plugin loader that lets tiddlers be specified in the plugin.info file. Since the format is very similar to the final format of the plugin tiddler once it's loaded it actually works out of the box. I've used this same principle to add a web-ready version to the bundle which can be loaded into the browser using a script tag, and can save serious bandwidth on smaller wikis. 

You can read all about it here: https://github.com/Arlen22/TiddlyWiki5-production

So I don't mind taking it out of the git repository, since it is actually copied from TiddlyWiki5-production, but it will need to be bundled in at some point in the build process as an asset. We could do it as an npm module if we have a dependable way of finding it. I'm guessing that would be `require.resolve('tiddlywiki5-production')`.

**Comment by Arlen22** [comment]
>but it will need to be bundled in at some point in the build process as an asset.

This is only necessary if we have a zip bundle distribution as opposed to telling people to do `npm install tiddlyserver`. I have two target audiences. Linux can easily use npm, but the other use case is portable setups where people keep everything on a flash drive. That one will need a zip bundle. However, tiddlywiki is released very infrequently, and so is TiddlyServer, so I can just do that manually for now. Up to now the repo has actually been completely portable.

**Comment by Arlen22** [comment]
Well, maybe npm install is easier all around, since people almost always have access to a computer to setup their portable stuff on. If someone is really in a bind, the manual instructions are quite simple, so it might not be a big problem.

**Review by Arlen22 — APPROVED** [review]
I'm liking what I'm seeing so far. I might have a few questions about the cookie auth stuff, but I'm still looking through it.

**Comment by someguynamedmatt** [comment]
Yeah, please tear it apart. Your knowledge of the system, as a whole, is more encompassing (obviously).

**Comment by Arlen22** [comment]
That whole cookie thing was a complete bug. Thanks for catching it.

**Comment by Arlen22** [comment]
I've subbed in the tiddlywiki npm directory for the moment until I figure out how I want to publish the bundled version.

**Comment by someguynamedmatt** [comment]
Sounds good. I’m out and about, but when I get back in front of my machine I’ll read through your other comments and try to understand things more thoroughly.

**Comment by Arlen22** [comment]
I'll wait for https://github.com/Arlen22/TiddlyServer/pull/83 until we get this one in.

Here are a few followup comments to my previous posts.

>The server[.js] file in the root is intended to be more of a bin file (like tiddlywiki.js) where as src/server.ts is the main entry point of the "library" part of TiddlyServer. I hope that makes sense.

I said that before looking through the code. I understand more clearly now what you're doing so for now I'm going to leave it as a .ts file.

> I remember one is in boot.js because it has a require call if a module is not found and therefore has to be accounted for. 

Actually it was in datafolder.ts where it called boot.js because boot.js needs to be from the target tiddlywiki directory rather than being compiled in when using webpack.

**Comment by Arlen22** [comment]
One more question. What linter/formatter do you use. It's slightly different than the one I use, and it might be more picky as well. The formatting changes looked pretty consistent so I'm guessing you must have some kind of formatter for that.

**Comment by someguynamedmatt** [comment]
It might be a global prettier configuration. I can set up the project with something definitive. If you have any strong opinions on options (double quotes, semi colons, etc) lemme know.

**Comment by Arlen22** [comment]
If you can add it in that's fine and I can modify it as needed.

**Comment by Arlen22** [comment]
The preflighter.js file is intended to be modified by the user. Not quite sure how I'm going to handle it using this layout. I might have server.ts check which folder it is in. I guess I could also have it specified in settings.json or on the command line. I'll come back to it later I guess once I get some of the other pieces put together.

**Comment by Arlen22** [comment]
Actually, if you're just using the defaults I can add it too. I think I figured it out.

**Comment by Arlen22** [comment]
Nevermind, sorry, I figured it out.

**Comment by Arlen22** [comment]
Well I like the state its in now, but I think I need to do a little more work on the tiddlywiki dependancy before I can merge it. I might also go straight to webpack instead of generating javascript files, though it sure is nice to have the declaration files there.

**Comment by someguynamedmatt** [comment]
It’s possible to do a combination of the two: webpack and manual copying. I had it working at one point, but it felt too hacky to me so I moved away from it. The .ts files and the .js files should be separated by both directories and build steps, imo. What would absolutely be needed in the build dir?

**Comment by Arlen22** [comment]
Ok, I created v2.2 branch and I'm going to merge it into that. It's enough of a breaking change to warrant it. It will also simplify the tiddlywiki dependency question.

**Comment by someguynamedmatt** [comment]
Cool. I have another PR which also refractors the top-level server file. That would go nicely in 2.2 as well, I think.

**Comment by Arlen22** [comment]
> It’s possible to do a combination of the two: webpack and manual copying. I had it working at one point, but it felt too hacky to me so I moved away from it. 

I've worked on it before and I use it in a lot of other projects, so I'll probably do it at some point. I think I actually had it setup for it already, but then I removed it because it was mostly pointless. Since we don't have the build files in the repo now, I'll probably build the whole thing using either `/server.ts` or `/src/server.ts` as the entry point. I'm not sure which yet, but `/src/server.ts` would probably be easier because of how it is already setup. 

> The .ts files and the .js files should be separated by both directories and build steps, imo. 

I've had good success doing them together using `ts-loader`. Either way, having the build directory like this separates things out and makes both options a whole lot easier. I use webpack regularly for work, so this one will be pretty easy. 

> What would absolutely be needed in the build dir?

I'm thinking that, with a couple exceptions, (settings.json for now), the build directory should contain everything it needs to be fully operational (except the node_modules directory of course -- that can be higher). 

So if `/server.ts` finds itself in a folder named build, it will go up one level to get the default settings.json location, but otherwise everything goes in the build folder. I'm making the exception so people don't accidentally run build:clean and lose their settings.json file (and so it's easier to develop).

**Comment by Arlen22** [comment]
Ok, I pushed the tiddlywiki-production bundle to npm, so I'm using that now.

**Comment by Arlen22** [comment]
Also, I prefer to keep the settings object attached to each request, so I modified it accordingly.

**Pull request merged**
